# Generated by Django 5.2 on 2025-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='was_approved',
            field=models.BooleanField(default=False),
        ),
    ]
