# Generated by Django 5.2 on 2025-05-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto'), ('BANK', 'Cuenta Bancaria'), ('CREDIT', 'Tarjeta de Crédito')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='households.household')),
            ],
        ),
    ]
