# Generated by Django 5.1.9 on 2025-06-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="functional_type",
            field=models.CharField(
                choices=[
                    ("BANK", "Cuenta Bancaria"),
                    ("CREDIT_CARD", "Tarjeta de Crédito"),
                    ("WALLET", "Billetera Digital"),
                    ("CASH", "Efectivo"),
                    ("OTHER", "Otro"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="chartofaccounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Activo"),
                    ("LIABILITY", "Pasivo"),
                    ("EQUITY", "Patrimonio"),
                    ("INCOME", "Ingreso"),
                    ("EXPENSE", "Gasto"),
                    ("BANK", "Cuenta Bancaria"),
                    ("CREDIT", "Tarjeta de Crédito"),
                ],
                max_length=50,
            ),
        ),
    ]
