# Generated by Django 5.1.9 on 2025-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("spending", "Spending"),
                            ("saving", "Saving"),
                            ("investment", "Investment"),
                            ("risk", "Risk"),
                            ("opportunity", "Opportunity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("action_taken", models.BooleanField(default=False)),
                ("action_description", models.TextField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="ai_aiinsigh_user_id_b7e124_idx"
                    ),
                    models.Index(
                        fields=["is_read"], name="ai_aiinsigh_is_read_ccfc7b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("query", "Query"),
                            ("analysis", "Analysis"),
                            ("prediction", "Prediction"),
                            ("recommendation", "Recommendation"),
                            ("alert", "Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("feedback", models.BooleanField(blank=True, null=True)),
                ("feedback_comment", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="ai_aiintera_user_id_fab6bf_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_aiintera_created_64d1fd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("cash_flow", "Cash Flow"),
                            ("spending", "Spending"),
                            ("saving", "Saving"),
                            ("risk", "Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prediction", models.JSONField()),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_date", models.DateField()),
                ("actual_result", models.JSONField(blank=True, null=True)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="ai_aipredic_user_id_ff2676_idx"
                    ),
                    models.Index(
                        fields=["prediction_date"],
                        name="ai_aipredic_predict_44d887_idx",
                    ),
                ],
            },
        ),
    ]
