# Generated by Django 5.1.9 on 2025-06-14 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("delete", "Delete"),
                            ("edit", "Edit"),
                            ("reject", "Reject"),
                            ("login", "Login"),
                            ("transaction", "Transaction Change"),
                            ("budget_edit", "Budget Edit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="What the action was performed on (username, module, transaction ID, etc.)",
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
